name: lts-sol
channels:
  - conda-forge
  - default
dependencies:
  - numpy
  - matplotlib
  - colorcet
  - cmocean
  - gdal=3
  - localtileserver
  - shapely
  - pip
  - jupyterlab
  - ipywidgets
  - ipyleaflet
  - folium
  - jupyter-server-proxy
