name: lts-sol
channels:
  - conda-forge
  - default
dependencies:
  - numpy
  - matplotlib
  - colorcet
  - cmocean
  - gdal
  - localtileserver[colormaps,jupyter]
  - shapely
  - pip
  - jupyterlab
  - ipywidgets
  - ipyleaflet
  - folium
